# action.yaml
name: Convert Jupyter Notebooks to Databricks Notebooks
author: https://www.github.com/rafaelvp-db
branding:
  icon: book
  color: gray-dark
description: |
  Simple action that converts Jupyter .ipynb files into
  Databricks Python notebooks (.py)

inputs:
  inputPath:
    description: 'Relative path to the folder containing Jupyter notebooks'
    required: true
  outputPath:
    description: 'Relative path to the folder to which DB notebooks will be output'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.7'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Convert Jupyter Notebooks to Databricks format
      id: get-square
      run: |
        mkdir -p ${{ inputs.outputPath }}
        python ${{ github.action_path }}/src/bryckster.py run --input_path ${{ inputs.inputPath }} --output_path ${{ inputs.outputPath }}
      shell: bash
    - name: Commit
      run: |
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global user.name 'github-actions[bot]'
        git add ${{ inputs.outputPath }}
        git commit -m "Convert to Databricks"
        git push origin ${{ github.head_ref || github.ref_name }}
      shell: bash
